[platformio]
src_dir = .

[env:due]
platform = atmelsam
board = due
framework = arduino
upload_port = COM9
upload_protocol = sam-ba
board_upload.use_1200bps_touch = yes
board_upload.wait_for_upload_port = yes
monitor_port = COM8
monitor_speed = 115200
monitor_eol = CR
lib_deps =
    arduino-libraries/SD
    sebnil/DueFlashStorage